from config.constants import ACTION_CYCLE_DIMMER, BUTTON_SHORT_INSTA, BUTTON_SHORT_RELEASE, \
    BUTTON_LONG_HOLD, BUTTON_LONG_INSTA, SHADE_COMMAND_TOGGLE_UP, SHADE_COMMAND_TOGGLE_DOWN

# Create a mapping between the button names and the actions linked to the different possible trigger modes

BUTTON_ENTITY_MAP = {
    "zolder_1": {BUTTON_SHORT_INSTA: 'Zolder'},
    "zolder_2": {BUTTON_SHORT_INSTA: 'Technische Ruimte'},
    "kookplaat_1": {BUTTON_SHORT_RELEASE: 'Keuken Spots', BUTTON_LONG_INSTA: 'Boost'},
    "speelkamer_screen_1": {BUTTON_SHORT_INSTA: ('Shade_Speelkamer', SHADE_COMMAND_TOGGLE_UP)},
    "speelkamer_screen_2": {BUTTON_SHORT_INSTA: ('Shade_Speelkamer', SHADE_COMMAND_TOGGLE_DOWN)},
    "speelkamer_deur_1": {},
    "speelkamer_deur_2": {BUTTON_SHORT_INSTA: 'Eetkamer'},
    "speelkamer_deur_3": {BUTTON_SHORT_INSTA: 'Speelkamer'},
    "speelkamer_deur_4": {BUTTON_SHORT_INSTA: 'Keuken'},
    "living_tv_1": {BUTTON_SHORT_INSTA: 'TV Wand'},
    "living_tv_2": {BUTTON_SHORT_INSTA: 'Keuken'},
    "living_tv_3": {BUTTON_SHORT_INSTA: 'TV spots'},
    "living_tv_4": {BUTTON_SHORT_INSTA: 'Eetkamer'},
    "living_screen_1": {BUTTON_SHORT_INSTA: ('Shade_Salon', SHADE_COMMAND_TOGGLE_UP)},
    "living_screen_2": {BUTTON_SHORT_INSTA: ('Shade_Salon', SHADE_COMMAND_TOGGLE_DOWN)},
    "living_thermostaat_1": {BUTTON_SHORT_INSTA: 'TV spots'},
    "living_thermostaat_2": {BUTTON_SHORT_RELEASE: 'TV Wand', BUTTON_LONG_HOLD: ('TV Wand', ACTION_CYCLE_DIMMER)},
    "gang_living_1": {BUTTON_SHORT_INSTA: 'Voordeur'},
    "gang_living_2": {BUTTON_SHORT_INSTA: 'Hal'},
    "gang_bureau_1": {BUTTON_SHORT_INSTA: 'Hal'},
    "bureau_1": {BUTTON_SHORT_INSTA: 'Bureau Pruts'},
    "toilet_1": {BUTTON_SHORT_INSTA: 'Toilet'},
    "keuken_1": {BUTTON_SHORT_INSTA: 'Keuken'},
    "keuken_2": {BUTTON_SHORT_INSTA: 'Ledstrip'},
    "keuken_3": {BUTTON_SHORT_INSTA: 'Berging'},
    "berging_1": {BUTTON_SHORT_RELEASE: 'Berging', BUTTON_LONG_INSTA: 'Garage'},
    "garage_poort_1": {BUTTON_SHORT_RELEASE: 'Garage', BUTTON_LONG_INSTA: 'SCENE Alles uit'},
    "garage_deur_1": {BUTTON_SHORT_RELEASE: 'Garage', BUTTON_LONG_INSTA: 'Berging'},
    "trap_beneden_1": {BUTTON_SHORT_RELEASE: 'Trap', BUTTON_LONG_INSTA: 'SCENE Boven uit'},
    "trap_wasplaats_1": {BUTTON_SHORT_RELEASE: 'Trap', BUTTON_LONG_INSTA: 'SCENE Beneden uit'},
    "trap_voorkant_1": {BUTTON_SHORT_INSTA: 'Trap'},
    "trap_ouders_1": {BUTTON_SHORT_INSTA: 'Trap'},
    "trap_badkamer_1": {BUTTON_SHORT_INSTA: 'Trap'},
    "kind_deur_1": {BUTTON_SHORT_RELEASE: 'Slaapkamer Daniel', BUTTON_LONG_HOLD: ('Slaapkamer Daniel', ACTION_CYCLE_DIMMER)},
    "ouders_deur_1": {BUTTON_SHORT_RELEASE: 'Slaapkamer Ouders', BUTTON_LONG_HOLD: ('Slaapkamer Ouders', ACTION_CYCLE_DIMMER)},
    "ouders_bed_1": {BUTTON_SHORT_RELEASE: 'Slaapkamer Ouders', BUTTON_LONG_HOLD: ('Slaapkamer Ouders', ACTION_CYCLE_DIMMER)},
    "ouders_screen_1": {BUTTON_SHORT_INSTA: ('Shade_Slaapkamer Ouders', SHADE_COMMAND_TOGGLE_UP)},
    "ouders_screen_2": {BUTTON_SHORT_INSTA: ('Shade_Slaapkamer Ouders', SHADE_COMMAND_TOGGLE_DOWN)},
    "dressing_1": {BUTTON_SHORT_INSTA: 'Dressing'},
    "badkamer_1": {BUTTON_SHORT_INSTA: 'Badkamer'},
    "badkamer_2": {BUTTON_SHORT_INSTA: 'Spiegel'},
    "badkamer_3": {BUTTON_SHORT_INSTA: 'SCENE douche'},
    "trap_zolder_1": {BUTTON_SHORT_INSTA: 'Zolder'},
    "beestje_1": {BUTTON_SHORT_RELEASE: 'Bureau Beestje', BUTTON_LONG_HOLD: ('Bureau Beestje', ACTION_CYCLE_DIMMER)},
    "wasplaats_1": {BUTTON_SHORT_INSTA: 'Wasplaats'},
}
