
# Create a mapping between the button names and the relais names: {'short': '', 'long': ''}, possibly add relais parameters and
# add a modifier for long and short press

BUTTON_ENTITY_MAP = {
    "zolder_1": {'short': 'Zolder', 'long': 'Zolder'},
    "zolder_2": {'short': 'Technische Ruimte', 'long': 'Technische Ruimte'},
    "kookplaat_1": {'short': 'Keuken Spots', 'long': 'Boost'},
    "speelkamer_screens_1": {'short': 'Speelkamer up', 'long': 'Speelkamer up'},
    "speelkamer_screens_2": {'short': 'Speelkamer down', 'long': 'Speelkamer down'},
    "speelkamer_deur_1": {'short': None, 'long': None},
    "speelkamer_deur_2": {'short': 'Eetkamer', 'long': 'Eetkamer'},
    "speelkamer_deur_3": {'short': 'Speelkamer', 'long': 'Speelkamer'},
    "speelkamer_deur_4": {'short': 'Keuken', 'long': 'Keuken'},
    "living_tv_1": {'short': 'TV Wand', 'long': 'TV Wand'},
    "living_tv_2": {'short': 'Keuken', 'long': 'Keuken'},
    "living_tv_3": {'short': 'TV spots', 'long': 'TV spots'},
    "living_tv_4": {'short': 'Eetkamer', 'long': 'Eetkamer'},
    "living_screen_1": {'short': 'Salon up', 'long': 'Salon up'},
    "living_screen_2": {'short': 'Salon down', 'long': 'Salon down'},
    "living_thermostaat_1": {'short': 'TV spots', 'long': 'TV spots'},
    "living_thermostaat_2": {'short': 'TV Wand', 'long': 'TV Wand'},
    "gang_living_1": {'short': 'Voordeur', 'long': 'Voordeur'},
    "gang_living_2": {'short': 'Hal', 'long': 'Hal'},
    "gang_bureau_1": {'short': 'Hal', 'long': 'Hal'},
    "bureau_1": {'short': 'Bureau Pruts', 'long': 'Bureau Pruts'},
    "toilet_1": {'short': 'Toilet', 'long': 'Toilet'},
    "keuken_1": {'short': 'Keuken', 'long': 'Keuken'},
    "keuken_2": {'short': 'Ledstrip', 'long': 'Ledstrip'},
    "keuken_3": {'short': 'Berging', 'long': 'Berging'},
    "berging_1": {'short': 'Berging', 'long': 'Garage'},
    "garage_poort_1": {'short': 'Garage', 'long': None},
    "garage_deur_1": {'short': 'Garage', 'long': 'Berging'},
    "trap_beneden_1": {'short': 'Trap', 'long': None},
    "trap_wasplaats_1": {'short': 'Trap', 'long': 'Trap'},
    "trap_voorkant_1": {'short': 'Trap', 'long': 'Trap'},
    "trap_ouders_1": {'short': 'Trap', 'long': 'Trap'},
    "trap_badkamer_1": {'short': 'Trap', 'long': 'Trap'},
    "kind_deur_1": {'short': 'Slaapkamer Daniel', 'long': 'Slaapkamer Daniel'},
    "ouders_deur_1": {'short': 'Slaapkamer Ouders', 'long': 'Slaapkamer Ouders'},
    "ouders_bed_1": {'short': 'Slaapkamer Ouders', 'long': 'Slaapkamer Ouders'},
    "ouders_screen_1": {'short': 'Slaapkamer Ouders up', 'long': 'Slaapkamer Ouders up'},
    "ouders_screen_2": {'short': 'Slaapkamer Ouders down', 'long': 'Slaapkamer Ouders down'},
    "dressing_1": {'short': 'Dressing', 'long': 'Dressing'},
    "badkamer_1": {'short': 'Badkamer', 'long': 'Badkamer'},
    "badkamer_2": {'short': 'Spiegel', 'long': 'Spiegel'},
    "badkamer_3": {'short': 'Douche', 'long': 'Boost'},
    "trap_zolder_1": {'short': 'Trap', 'long': 'Trap'},
    "beestje_1": {'short': 'Bureau Beestje', 'long': 'Bureau Beestje'},
    "wasplaats_1": {'short': 'Wasplaats', 'long': 'Wasplaats'},
}