DOBISS_RELAY = 'relay'
DOBISS_DIMMER = 'dimmer'
DOBISS_SCENE = 'scene'
DOBISS_SHADE = 'shade'
LIGHT = 'light'
VENTILATION = 'fan'
SHADE = 'cover'

ACTION_SWITCH = 'switch'
ACTION_TURN_ON = 'turn_on'
ACTION_TURN_OFF = 'turn_off'
ACTION_SET_STATUS = 'set_status'
ACTION_SCHEDULE = 'schedule'
ACTION_CALL_FUNCTION = 'call_function'
ACTION_CYCLE_DIMMER = 'cycle_dimmer'
